build:
    environment:
        node: v8.11.2
        php:
            version: 7.2
            ini:
                date.timezone: "UTC"
    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run
                    - php-scrutinizer-run
        tests:
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=clover.xml tests/'
                        stop_on_failure: true
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'

filter:
    excluded_paths:
        - '.github/'
        - 'bin/'
        - 'config/'
        - 'public/'
        - 'templates/'
        - 'translations/'
        - 'var/'
    dependency_paths:
        - 'node_modules/'
        - 'vendor/'

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9.0)'
    - 'project.metric("scrutinizer.test_coverage", < 0.9)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.01)'