language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  mariadb: '10.2'

services:
  - mysql

env:
  global:
    - CODECOVERAGE=0

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'

before_install:
  - composer self-update
  - php -i
  - php -m

install:
  - composer install
  - composer require zendframework/zend-ldap

script:
  - composer validate --no-check-all --strict
  - composer kimai:codestyle
  - composer kimai:phpstan
  - vendor/bin/phpunit tests/
  - cp tests/.env.dist.sqlite .env
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:migrations:migrate first -n
