version: '3.4'

services:
    apache_kimai:
        image: hub.dev.noa-world.ch:443/apache-dev-72
        environment:
            - APP_ENV=dev
            - JWT_PUBLIC_KEY=SecretKeyChangeOnProd
            - DATABASE_URL=mysql://root:root@mysql_kimai/kimai
            - ADMINMAIL=kimai@example.com
            - ADMINPASS=changeme123
        ports:
            - 9090:80
        volumes:
            - ./:/var/www
            - ./build/dev/virtual_host.conf:/etc/apache2/sites-enabled/default.conf
        depends_on:
            - mysql_kimai

    mysql_kimai:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-storage-engine innodb
        ports:
            - 3333:3306
        environment:
            - MYSQL_DATABASE=kimai
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
