version: '3.4'

services:
    mysql_kimai:
        image: mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3301:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
    apache_kimai:
        image: hub.dev.noa-world.ch:443/apache-dev-72
        environment:
            - APP_ENV=dev
            - APP_HOST=localhost
            - APP_PROTO=http
            - JWT_PUBLIC_KEY=SecretKeyChangeOnProd
            - DATABASE_URL=mysql://root:root@mysql_kimai/kimai
            - ADMINMAIL=kimai@example.com
            - ADMINPASS=changeme123
        ports:
            - 9090:80
        volumes:
            - ./:/var/www
            - ./build/dev/virtual_host.conf:/etc/apache2/sites-enabled/default.conf
        depends_on:
            - mysql_kimai
