version: '3.4'

services:
  kimai:
    image: hub.dev.noa-world.ch:443/apache-dev-72
    ports:
      - 9090:80
    volumes:
      - ./:/var/www
      - ./build/dev/virtual_host.conf:/etc/apache2/sites-enabled/default.conf
  mysql:
    image: mysql:5.7
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
