App\Entity\Project:
    exclusion_policy: All
    custom_accessor_order: [id, name, comment, visible, budget, orderNumber, customer, fixedRate, hourlyRate, color]
    properties:
        id:
            include: true
        name:
            include: true
        comment:
            include: true
            groups: [Entity]
        visible:
            include: true
        budget:
            include: true
            groups: [Entity]
        orderNumber:
            include: true
            groups: [Entity]
        fixedRate:
            include: true
            groups: [Project]
        hourlyRate:
            include: true
            groups: [Project]
        customer:
            groups: [Subresource]
        color:
            include: true
    virtual_properties:
        getCustomer:
            serialized_name: customer
            exp: "object.getCustomer() === null ? null : object.getCustomer().getId()"
            type: integer
            groups: [Entity, Collection]
